### ISSUE TITLE
Uncaught TypeError: treeview.serialize is not a function

### ISSUE THREAD

**Issue by tastytentacles** [jeremyfa/atom-lime#14]
trying to add a live project file and I get this

**Atom**: 1.17.2 x64
**Electron**: 1.4.16
**OS**: linux 4.11.3-1-ARCH
**Thrown From**: [lime](https://github.com/jeremyfa/atom-lime) package 0.3.5

### Stack Trace

Uncaught TypeError: treeview.serialize is not a function

```
At /home/sk/.atom/packages/lime/lib/lime.js:200

TypeError: treeview.serialize is not a function
    at Object.set_lime_file_from_treeview (/packages/lime/lib/lime.js:200:36)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:265:29)
    at CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/lib/atom/src/command-registry.js:166:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/usr/lib/atom/src/atom-environment.js:1300:28)
    at EventEmitter.outerCallback (/usr/lib/atom/src/application-delegate.js:333:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  2x -1:49.2.0 core:confirm (input.hidden-input)
     -0:03.3.0 lime:set-lime-file (span.name.icon.icon-file-text)
```

### Non-Core Packages

```
busy-signal 1.4.1 
haxe 0.8.14 
intentions 1.1.2 
language-haxe 0.6.0 
lime 0.3.5 
linter 2.1.4 
linter-ui-default 1.6.0 
MagicPython 1.0.10 
minimap 4.28.2 
monokai-seti 0.9.0 
seti-ui 1.8.0 
```

**Comment by tastytentacles** [comment]
yah IDK why you closed this, still getting the error on a fresh install almost a year latter, is there a list of dependants I might be missing or something?

the list on the install page is less then useless, "linter" might refer to any of 3 packages from what I can tell.

**Comment by Nidrop** [comment]
I have the same error on Windows 7 x64. Atom version 1.27.1

**Comment by tastytentacles** [comment]
my recommendation @Nidrop is to burn Atom as a haxe IDE and just use Flash Develop, especially if you are on windows. Sublime text if you need code completion on Linux, the plug in is not quite as good as Flash Develop IMO when it comes to completing packages but it works for the most part and can manage error handleing.
