### ISSUE TITLE
Failed to activate the lime package

### ISSUE THREAD

**Issue by AlexFlasch** [jeremyfa/atom-lime#2]
[Enter steps to reproduce below:]
1. Go to update packages. (haxe, lime, and sass-autocompile were in my available updates list)
2. Click Update All.

**Atom Version**: 1.0.2
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [lime](https://github.com/jeremyfa/atom-lime) package, v0.3.0
### Stack Trace

Failed to activate the lime package

```
At Can't register a command with non-function callback.

Error: Can't register a command with non-function callback.
  at CommandRegistry.module.exports.CommandRegistry.add (C:\Users\Alex\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:44:15)
  at Object.module.exports._command (C:\Users\Alex\.atom\packages\lime\lib\lime.js:209:33)
  at Object.module.exports._init_internal (C:\Users\Alex\.atom\packages\lime\lib\lime.js:196:14)
  at Object.module.exports.activate (C:\Users\Alex\.atom\packages\lime\lib\lime.js:27:14)
  at Package.module.exports.Package.activateNow (C:\Users\Alex\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:240:19)
  at C:\Users\Alex\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:221:30
  at Package.module.exports.Package.measure (C:\Users\Alex\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:165:15)
  at Package.module.exports.Package.activate (C:\Users\Alex\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:213:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Alex\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package-manager.js:452:21)
  at C:\Users\Alex\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:312:60
  at exit (C:\Users\Alex\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:59:16)
  at triggerExitCallback (C:\Users\Alex\AppData\Local\atom\app-1.0.2\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\Alex\AppData\Local\atom\app-1.0.2\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```
### Commands

```
     -7:44.1.0 command-palette:toggle (atom-text-editor.editor.mini.is-focused)
     -7:29.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -7:29.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -7:29.2.0 editor:consolidate-selections (atom-text-editor.editor.mini)
     -7:29.2.0 core:cancel (atom-text-editor.editor.mini)
  9x -7:26 core:backspace (atom-text-editor.editor.mini.is-focused)
     -7:23.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:39 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax.theme-atom-material-ui)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "disabledPackages": [
      "autocomplete-haxe",
      "ide-haskell",
      "language-haskell"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.0
atom-material-syntax, v0.2.1
atom-material-ui, v0.5.9
auto-indent, v0.5.0
color-picker, v2.0.11
conceal, v0.0.1
docblockr, v0.7.3
editorconfig, v1.0.1
emmet, v2.3.12
flow, v0.4.0
haxe, v0.8.4
language-haxe, v0.3.0
lime, v0.3.0
linter, v1.2.4
minimap, v4.12.0
pigments, v0.9.0
sass-autocompile, v0.7.3

# Dev
No dev packages
```

**Comment by jeremyfa** [comment]
Does the plugin work normally after restarting Atom?

**Comment by AlexFlasch** [comment]
It seems as though it does. If I'm honest I haven't really used the lime plugin. :) The error may have been caused by some other broken plugins as I was getting some errors before this one if I remember right.

**Comment by jeremyfa** [comment]
I close it for now then, and will reopen if similar issues are reported.

**Comment by jeremyfa** [comment]
There was indeed a problem, easily reproducible by just disabling/enabling the plugin. Thanks for the report!

**Comment by Etskh** [comment]
Same issue for Mac OSX:

[Enter steps to reproduce below:]
1. Disable atom-lime
2. Enable atom-lime

**Atom Version**: 1.0.7
**System**: Mac OS X 10.9.4
**Thrown From**: [lime](https://github.com/jeremyfa/atom-lime) package, v0.3.1

### Stack Trace

Failed to activate the lime package

```
At Can't register a command with non-function callback.

Error: Can't register a command with non-function callback.
  at CommandRegistry.module.exports.CommandRegistry.add (/Applications/Devel/Atom.app/Contents/Resources/app.asar/src/command-registry.js:44:15)
  at Object.module.exports._command (/Users/james_loucks/.atom/packages/lime/lib/lime.js:209:33)
  at Object.module.exports._init_internal (/Users/james_loucks/.atom/packages/lime/lib/lime.js:196:14)
  at Object.module.exports.activate (/Users/james_loucks/.atom/packages/lime/lib/lime.js:27:14)
  at Package.module.exports.Package.activateNow (/Applications/Devel/Atom.app/Contents/Resources/app.asar/src/package.js:243:19)
  at /Applications/Devel/Atom.app/Contents/Resources/app.asar/src/package.js:224:30
  at Package.module.exports.Package.measure (/Applications/Devel/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Applications/Devel/Atom.app/Contents/Resources/app.asar/src/package.js:216:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Devel/Atom.app/Contents/Resources/app.asar/src/package-manager.js:486:21)
  at /Applications/Devel/Atom.app/Contents/Resources/app.asar/src/package-manager.js:314:19
  at /Applications/Devel/Atom.app/Contents/Resources/app.asar/src/config.js:574:20
  at Emitter.module.exports.Emitter.emit (/Applications/Devel/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/Applications/Devel/Atom.app/Contents/Resources/app.asar/src/config.js:736:29)
  at Config.module.exports.Config.setRawValue (/Applications/Devel/Atom.app/Contents/Resources/app.asar/src/config.js:551:19)
  at Config.module.exports.Config.set (/Applications/Devel/Atom.app/Contents/Resources/app.asar/src/config.js:233:14)
  at Config.module.exports.Config.removeAtKeyPath (/Applications/Devel/Atom.app/Contents/Resources/app.asar/src/config.js:343:12)
  at Package.module.exports.Package.enable (/Applications/Devel/Atom.app/Contents/Resources/app.asar/src/package.js:152:26)
  at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Devel/Atom.app/Contents/Resources/app.asar/src/package-manager.js:143:14)
  at HTMLButtonElement.<anonymous> (/Applications/Devel/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:314:27)
  at HTMLButtonElement.jQuery.event.dispatch (/Applications/Devel/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (/Applications/Devel/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -2:57.1.0 core:save (input.hidden-input)
  2x -2:53.1.0 core:backspace (input.hidden-input)
  2x -2:52.6.0 core:confirm (input.hidden-input)
  2x -2:45.8.0 editor:newline (input.hidden-input)
  7x -2:42.7.0 core:backspace (input.hidden-input)
  2x -2:37.4.0 editor:newline (input.hidden-input)
     -2:36.1.0 core:move-down (input.hidden-input)
     -2:35.6.0 core:move-up (input.hidden-input)
     -2:35.2.0 snippets:next-tab-stop (input.hidden-input)
     -2:35.2.0 snippets:expand (input.hidden-input)
     -2:35.2.0 editor:indent (input.hidden-input)
     -2:34.6.0 core:backspace (input.hidden-input)
     -2:30.1.0 core:save (input.hidden-input)
     -2:21.8.0 editor:newline (input.hidden-input)
 10x -2:21.1.0 core:backspace (input.hidden-input)
     -2:00.5.0 core:save (input.hidden-input)
```

### Config

``` json
{
  "core": {},
  "lime": {
    "debug_logging": true,
    "lime_default_target": "cpp"
  }
}
```

### Installed Packages

``` coffee
# User
autocomplete-clang, v0.8.7
haxe, v0.8.7
language-haxe, v0.3.0
lime, v0.3.1
linter, v1.4.3

# Dev
No dev packages
```
